package net.otgon.backend.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.test.context.ActiveProfiles;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("JwtService unit tests")
@ActiveProfiles("test")
public class JwtTest {

    private JwtService jwtService;
    String username = "alice";
    String validToken = null;

    @BeforeEach
    public void setUp() {
        jwtService = new JwtService("test-secret-key-must-be-long-enough-for-hmac256");
        validToken = jwtService.generateToken(username);
    }
    //TEST-1 SUCCESS PATH WHEN EXTRACTING USERNAME FROM TOKEN
    @Test
    @DisplayName("Success path: extract username")
    void extractUsernameTestSuccessPath() {

        //Act
        String extractedUsername = jwtService.extractUsername(validToken);

        //Assert
        assertEquals(username, extractedUsername);
    }

    //TEST-2 SUCCESS PATH WHEN GENERATING TOKEN WITH USERNAME
    @Test
    @DisplayName("Success path: generate token")
    void generateTokenTestSuccessPath() {

        //Arrange, act
        String token = jwtService.generateToken(username);
        //Assert
        assertNotNull(token);
        assertEquals(3, token.split("\\.").length);
        assertEquals(username, jwtService.extractUsername(token));
    }

    //TEST-3 FAIL WHEN INVALID TOKEN
    @Test
    @DisplayName("Fail: invalid token")
    void extractUsernameFailInvalidToken() {

        //Arrange
        String invalidToken = "invalid.token";

        //Act & Assert
        RuntimeException exception = assertThrows(
                RuntimeException.class,
                () -> jwtService.extractUsername(invalidToken),
                "Expected exception");

        assertEquals("Invalid token", exception.getMessage());
    }

    //TEST-4 FAIL WHEN TOKEN IS EXPIRED
    @Test
    @DisplayName("Fail: expired token")
    void extractUsernameFailExpiredToken() {

        //Arrange
        String expiredToken = jwtService.generateExpiredTokenForTesting(username);

        //Act & Assert
        RuntimeException exception = assertThrows(
                RuntimeException.class,
                () -> jwtService.extractUsername(expiredToken),
                "Expected exception");
        assertEquals("Token expired", exception.getMessage());
    }

    //TEST-5 FAIL WHEN TOKEN IS GENERATED USING DIFFERENT SECRET KEY
    @Test
    @DisplayName("Fail: token is generated by different service")
    void extractUsernameFailDifferentSecretKey() {

        //Arrange
        JwtService otherService = new JwtService("different-test-secret-key-must-be-long-enough-for-hmac256");
        String otherJwtToken = otherService.generateToken(username);

        //Act & Assert
        RuntimeException exception = assertThrows(
                RuntimeException.class,
                () -> jwtService.extractUsername(otherJwtToken),
                "Expected exception");
        assertEquals("Invalid token", exception.getMessage());
    }
}
