name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Testing
        run: mvn test

      - name: Run security scanning
        run: |
          curl -f --max-time 60 -X POST https://api-security-scanner-1.onrender.com/api/scan/validate \
          -H "Content-Type: application/json" \
          -d '{"specUrl": "https://virtual-card-spring-boot-backend.onrender.com/v3/api-docs"}'


